<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>apigee</groupId>
    <artifactId>BasicAuth</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <pluginRepositories>
        <pluginRepository>
            <id>central</id>
            <name>Maven Plugin Repository</name>
            <url>https://repo1.maven.org/maven2</url>
        </pluginRepository>
    </pluginRepositories>

    <build>
        <plugins>
            <plugin>
                <groupId>io.apigee.build-tools.enterprise.maven</groupId>
                <artifactId>apigee-edge-maven-plugin</artifactId>
                <version>2.3.5</version>
                <executions>
                    <execution>
                        <id>configure-bundle-step</id>
                        <phase>package</phase>
                        <goals>
                            <goal>configure</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>deploy-bundle-step</id>
                        <phase>install</phase>
                        <goals>
                            <goal>deploy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>eval</id>
            <properties>
                <apigee.profile>eval</apigee.profile>
                <apigee.env>eval</apigee.env>
                <apigee.hosturl>https://apigee.googleapis.com</apigee.hosturl>
                <apigee.apiversion>v1</apigee.apiversion>
                <apigee.org>${org}</apigee.org> <!-- Passed from GitHub Action -->
                <apigee.options>update</apigee.options>
            </properties>
        </profile>
    </profiles>
</project>
